defmodule Example.Repo.Migrations.InitialCmsSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cms_sites, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :meta, :map, default: %{}
      add :custom_js, :text
      add :custom_css, :text
      add :js_url, :text
      add :css_url, :text
      add :description, :text
      add :domain, :text
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:cms_sites, [:domain], name: "cms_sites_unique_domain_index")

    create unique_index(:cms_sites, [:slug], name: "cms_sites_unique_slug_index")

    create table(:cms_pages, primary_key: false) do
      add :layout_id,
          references(:cms_layouts, column: :id, name: "cms_pages_layout_id_fkey", type: :uuid)

      add :site_id,
          references(:cms_sites, column: :id, name: "cms_pages_site_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :sort_order, :bigint
      add :custom_js, :text
      add :custom_css, :text
      add :og_image_url, :text
      add :meta_description, :text
      add :meta_title, :text
      add :published_at, :utc_datetime
      add :published, :boolean
      add :editor_mode, :text
      add :template, :text
      add :content, :map
      add :description, :text
      add :slug, :text, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:cms_media, primary_key: false) do
      add :site_id,
          references(:cms_sites, column: :id, name: "cms_media_site_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :folder, :text
      add :alt_text, :text
      add :metadata, :map, default: %{}
      add :storage_backend, :text
      add :storage_path, :text, null: false
      add :url, :text, null: false
      add :size, :bigint, null: false
      add :content_type, :text, null: false
      add :filename, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:cms_layouts, primary_key: false) do
      add :site_id,
          references(:cms_sites, column: :id, name: "cms_layouts_site_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :is_default, :boolean
      add :template, :text, null: false
      add :description, :text
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:cms_pages, [:site_id, :slug],
             name: "cms_pages_unique_slug_per_site_index"
           )

    create unique_index(:cms_layouts, [:site_id, :slug],
             name: "cms_layouts_unique_slug_per_site_index"
           )

    create table(:cms_components, primary_key: false) do
      add :site_id,
          references(:cms_sites, column: :id, name: "cms_components_site_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :preview_thumbnail, :text
      add :default_props, :map, default: %{}
      add :props_schema, :map, default: %{}
      add :template, :text, null: false
      add :category, :text, null: false
      add :icon, :text
      add :description, :text
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:cms_components, [:site_id, :slug],
             name: "cms_components_unique_slug_per_site_index"
           )
  end

  def down do
    drop_if_exists unique_index(:cms_components, [:site_id, :slug],
                     name: "cms_components_unique_slug_per_site_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cms_components` table without the `cms_components_site_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:cms_components)

    drop_if_exists unique_index(:cms_layouts, [:site_id, :slug],
                     name: "cms_layouts_unique_slug_per_site_index"
                   )

    drop_if_exists unique_index(:cms_pages, [:site_id, :slug],
                     name: "cms_pages_unique_slug_per_site_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cms_layouts` table without the `cms_layouts_site_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:cms_layouts)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cms_media` table without the `cms_media_site_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:cms_media)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cms_pages` table without the `cms_pages_site_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `cms_pages` table without the `cms_pages_layout_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:cms_pages)

    drop_if_exists unique_index(:cms_sites, [:slug], name: "cms_sites_unique_slug_index")

    drop_if_exists unique_index(:cms_sites, [:domain], name: "cms_sites_unique_domain_index")

    drop table(:cms_sites)
  end
end